# Generated by Django 4.2.13 on 2024-05-13 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Igra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Tip', models.CharField(choices=[('A', 'Admin'), ('M', 'Moderator'), ('I', 'Igrac'), ('G', 'Gost')], max_length=1)),
                ('Ime', models.CharField(max_length=255, null=True)),
                ('Prezime', models.CharField(max_length=255, null=True)),
                ('BrojTrofeja', models.IntegerField(default=0)),
                ('BrojPoena', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turnir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MrezaBrojeva',
            fields=[
                ('igra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.igra')),
                ('TrazeniBroj', models.IntegerField()),
                ('PomocniBroj1', models.IntegerField()),
                ('PomocniBroj2', models.IntegerField()),
                ('PomocniBroj3', models.IntegerField()),
                ('PomocniBroj4', models.IntegerField()),
                ('PomocniBroj5', models.IntegerField()),
                ('PomocniBroj6', models.IntegerField()),
            ],
            options={
                'verbose_name': 'MrezaBrojeva',
                'verbose_name_plural': 'MrezaBrojeva',
            },
            bases=('app.igra',),
        ),
        migrations.CreateModel(
            name='PaukovaSifra',
            fields=[
                ('igra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.igra')),
                ('TrazenaRec', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'PaukovaSifra',
                'verbose_name_plural': 'PaukovaSifra',
            },
            bases=('app.igra',),
        ),
        migrations.CreateModel(
            name='SkokNaMrezu',
            fields=[
                ('igra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.igra')),
                ('Postavka', models.TextField()),
                ('Odgovor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'SkokNaMrezu',
                'verbose_name_plural': 'SkokNaMrezu',
            },
            bases=('app.igra',),
        ),
        migrations.CreateModel(
            name='Umrezavanje',
            fields=[
                ('igra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.igra')),
                ('TekstPitanja', models.TextField()),
                ('Postavka1', models.CharField(max_length=20)),
                ('Odgovor1', models.CharField(max_length=20)),
                ('Postavka2', models.CharField(max_length=20)),
                ('Odgovor2', models.CharField(max_length=20)),
                ('Postavka3', models.CharField(max_length=20)),
                ('Odgovor3', models.CharField(max_length=20)),
                ('Postavka4', models.CharField(max_length=20)),
                ('Odgovor4', models.CharField(max_length=20)),
                ('Postavka5', models.CharField(max_length=20)),
                ('Odgovor5', models.CharField(max_length=20)),
                ('Postavka6', models.CharField(max_length=20)),
                ('Odgovor6', models.CharField(max_length=20)),
                ('Postavka7', models.CharField(max_length=20)),
                ('Odgovor7', models.CharField(max_length=20)),
                ('Postavka8', models.CharField(max_length=20)),
                ('Odgovor8', models.CharField(max_length=20)),
                ('Postavka9', models.CharField(max_length=20)),
                ('Odgovor9', models.CharField(max_length=20)),
                ('Postavka10', models.CharField(max_length=20)),
                ('Odgovor10', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Umrezavanje',
                'verbose_name_plural': 'Umrezavanje',
            },
            bases=('app.igra',),
        ),
        migrations.CreateModel(
            name='UtekniPauku',
            fields=[
                ('igra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.igra')),
                ('TrazenaRec', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'UtekniPauku',
                'verbose_name_plural': 'UtekniPauku',
            },
            bases=('app.igra',),
        ),
        migrations.CreateModel(
            name='Ucestvuje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OsvojenoMesto', models.IntegerField(default=0)),
                ('OsvojeniBrojTrofeja', models.IntegerField(default=0)),
                ('Korisnik', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.korisnik')),
                ('Turnir', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.turnir')),
            ],
        ),
        migrations.CreateModel(
            name='Okrsaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Igrac1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='app.korisnik')),
                ('Igrac2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='app.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='OdigranaIgra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Igrac1Poeni', models.IntegerField()),
                ('Igrac2Poeni', models.IntegerField()),
                ('Igra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.igra')),
                ('Okrsaj', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.okrsaj')),
            ],
        ),
    ]
